main.go
pkg/options/options.go

added tls enabled services

---

pkg/collectors/policyreport.go

use namespace for clustername

---

Dockerfile

Issue: https://github.com/open-cluster-management/backlog/issues/13278

Update base docker image to 8.4

---

README.md

For https://github.com/open-cluster-management/backlog/issues/13851

Dummy update to trigger image build

---

README.md

Issue: https://github.com/open-cluster-management/backlog/issues/14444

[2.3] Update docker image

---

README.md

For https://github.com/open-cluster-management/backlog/issues/15245

[release 2.3] image rebuild 2.3

---

README.md

Signed-off-by: Sherin Varughese <shvarugh@redhat.com>
Things to check for while merging to main:
Jobs exist and pass for 
Other checks:

rebuild image for checking Prow

---

.gitignore
.travis.yml
Dockerfile
Makefile
Makefile.prow
README.md
go.mod

Signed-off-by: Sherin Varughese <shvarugh@redhat.com>
Related Issue: open-cluster-management/backlog#15572

[release 2.3] update 2.3 to go 1.17

---

README.md

Signed-off-by: dislbenn <lavontae.bennett@gmail.com>

Rebuilding file to trigger sonar scan

---

pkg/collectors/builder_test.go

Signed-off-by: xavier dharmaiyan <xavier@redhat.com>

added builder test

---

README.md

Signed-off-by: Anxhela <acoba@redhat.com>
**Related Issue:**  stolostron/backlog#22453
No-op pr to trigger image scan

No-op pr to trigger image scan

---

Dockerfile

Signed-off-by: Zack Layne <zlayne@redhat.com>
**Related Issue:**  https://github.com/stolostron/backlog/issues/24212

[2.5] Update to golang 1.18

---

go.mod

Signed-off-by: Zack Layne <zlayne@redhat.com>
**Related Issue:**  stolostron/backlog#24212

[2.5] update go.mod to 1.18

---

Dockerfile
go.mod

Signed-off-by: Zack Layne <zlayne@redhat.com>
**Related Issue:**  https://github.com/stolostron/backlog/issues/24212

[2.4] Update to golang 1.18

---

README.md

**Issue:** stolostron/backlog/issues/24842
Created using automation.

[main] Trigger prow rebuild 2022-09-19

---

main.go

**Related Issue:** https://issues.redhat.com/browse/ACM-4379

ACM 4379 add timeout

---

main.go

**Related Issue:**  https://issues.redhat.com/browse/ACM-4379
https://issues.redhat.com/browse/ACM-4379

add read timeout to server

---

renovate.json

- Update konflux renovate schedule

Update konflux renovate schedule

---

OWNERS

add smcavey owners 2.11

---

OWNERS

add smcavey to 2.10 owners

---

OWNERS

add smcavey to 2.12 owners

---

pkg/collectors/policyreport.go
pkg/collectors/policyreport_test.go

Because GRC policy results are named based on the Policy, but created for each template, there can be multiple entries in the PolicyReport results for what looks like the 'same' policy. If all of the metric labels would be the same for any of those entries (eg, excluding the description field), then a `PrometheusDuplicateTimestamps` alert might be fired.
Now, duplicate results in a PolicyReport will increment the value of the metric, instead of being incorrectly reported multiple times. This handles not only the GRC case, but any source that puts results in the PolicyReport.
Refs:
- https://issues.redhat.com/browse/ACM-16014

Deduplicate metrics from policy report results

---

.tekton/insights-metrics-acm-210-pull-request.yaml
.tekton/insights-metrics-acm-210-push.yaml

**Related Issue:**  https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.3/MIGRATION.md
- Update konflux config

[release-2.10] Update Konflux config

---

.tekton/insights-metrics-acm-211-pull-request.yaml
.tekton/insights-metrics-acm-211-push.yaml

**Related Issue:**  https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.3/MIGRATION.md
- Update konflux config

[release-2.11] Update Konflux config

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod

Update to go 1.23 and UBI 9

---

go.mod
go.sum

https://www.cve.org/CVERecord?id=CVE-2025-22868
https://www.cve.org/CVERecord?id=CVE-2025-22869
Updated affected libraries

CVE-2025-22868/22869

---

Dockerfile
Dockerfile.rhtap
Makefile
Makefile.prow
go.mod
go.sum

Manual cherry-pick of dca74af9b90f05ddc7ec8f97d6707707db1c9bee

release 2.12 Update to go 122

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod

cherry-pick of https://github.com/stolostron/insights-metrics/pull/213

[release-2.13] Update to go 1.23 and UBI 9 (#213)

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod

cherry-pick of https://github.com/stolostron/insights-metrics/pull/213

[release-2.12] Update to go 1.23 and UBI 9 (#213)

---

go.mod
go.sum

fix cves like https://github.com/stolostron/insights-metrics/pull/224

[release-2.11] fix cve-2025-22868/22869

---

.ci-operator.yaml
Dockerfile
Makefile
Makefile.prow
go.mod
go.sum

Added .ci-operator.yaml and updated go to 1.23

[release-2.9] update go to 1.23

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
Makefile
Makefile.prow
go.mod
go.sum

Added .ci-operator.yaml file and updated go to 1.23

[release-2.10] go 123 update

---

.tekton/insights-metrics-acm-210-pull-request.yaml

- Added missing params image-digest and image-url to fix https://github.com/stolostron/insights-metrics/pull/302

[release-2.10] fix sast-snyk-check add missing params

---

.tekton/insights-metrics-acm-211-pull-request.yaml

- Added missing params image-digest and image-url to fix https://github.com/stolostron/insights-metrics/pull/305

[release-2.11] fix sast-snyk-check add missing params

---

.tekton/insights-metrics-acm-214-pull-request.yaml

- Added image-digest param to fix https://github.com/stolostron/insights-metrics/pull/301

fix sast-coverity-check-oci-ta add missing param

---

.tekton/insights-metrics-acm-211-pull-request.yaml

- moved params according to https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1745404637499059?thread_ts=1745339419.829389&cid=C04PZ7H0VA8

[release-2.11] fix sast-snyk-check params

---

.tekton/insights-metrics-acm-214-push.yaml

https://issues.redhat.com/browse/ACM-0000
- Added ...

fix on push konflux config

---

.tekton/insights-metrics-acm-211-push.yaml

https://issues.redhat.com/browse/ACM-0000
- Added ...

[release-2.11] fix konflux on push config

---

.tekton/insights-metrics-acm-210-push.yaml

https://issues.redhat.com/browse/ACM-0000
- Added ...

[release-2.10] fix konflux on push config

---

.tekton/insights-metrics-acm-214-pull-request.yaml
.tekton/insights-metrics-acm-214-push.yaml

main multiarch builds

---

.tekton/insights-metrics-acm-215-push.yaml

- fix konflux on push cel-expression target branch

fix konflux on push cel-expression target branch

---

.tekton/insights-metrics-acm-214-pull-request.yaml

N/A
- Update konflux to run on PRs to release-2.14

[release-2.14] Update konflux to run on PRs to release-2.14

---

.tekton/insights-metrics-acm-210-pull-request.yaml
.tekton/insights-metrics-acm-210-push.yaml

- migration https://github.com/konflux-ci/build-definitions/blob/main/task/source-build/0.3/MIGRATION.md

[release-2.10] build-source-image migration

---

.tekton/insights-metrics-acm-212-pull-request.yaml
.tekton/insights-metrics-acm-212-push.yaml
Dockerfile
Dockerfile.rhtap

- Added multi arch and hermetic builds

[release-2.12] multi arch and hermetic builds

---

.tekton/insights-metrics-acm-211-pull-request.yaml
.tekton/insights-metrics-acm-211-push.yaml
Dockerfile
Dockerfile.rhtap

- Added multi arch and hermetic builds

[release-2.11] mutli arch and hermetic builds

---

.ci-operator.yaml
Dockerfile
Dockerfile.rhtap
go.mod

[release-2.11] update go to 1.24 (#474)
